[package]
name = "l1x-test-utility"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.14" }
lazy_static = "1.4.0"
anyhow = "1.0.71"
rand = "0.8.5"
sha2 = "0.10.8"
l1x-sdk-primitives = { path = "../l1x-sdk-primitives" }
